services:
  db:
    image: postgres:18
    container_name: nestjs-starter-template-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs-starter-template-db
    ports:
      - "5432:5432"
    volumes:
      - nestjs-starter-template-db-volume:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:4-management
    container_name: nestjs-starter-template-rabbitmq
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - nestjs-starter-template-rabbitmq-volume:/var/lib/rabbitmq

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: nestjs-starter-template-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:latest
    container_name: nestjs-starter-template-tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # query port for grafana

  grafana:
    image: grafana/grafana:latest
    container_name: nestjs-starter-template-grafana
    ports:
      - "3900:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - nestjs-starter-template-grafana-volume:/var/lib/grafana

  # api:
  #   build:
  #     context: ..
  #     dockerfile: ./docker/Dockerfile.api
  #   image: nestjs-starter-api:latest
  #   container_name: nestjs-starter-template-api
  #   restart: always
  #   env_file: ../.env
  #   environment:
  #     NODE_ENV: production
  #     DATABASE_HOSTNAME: db
  #     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - rabbitmq

  # worker:
  #   build:
  #     context: ..
  #     dockerfile: ./docker/Dockerfile.worker
  #   image: nestjs-starter-worker:latest
  #   container_name: nestjs-starter-template-worker
  #   restart: always
  #   env_file: ../.env
  #   environment:
  #     NODE_ENV: production
  #     DATABASE_HOSTNAME: db
  #     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
  #   depends_on:
  #     - db
  #     - rabbitmq

  # s3:
  #   image: rustfs/rustfs:latest
  #   container_name: nestjs-starter-template-rustfs
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     RUSTFS_ACCESS_KEY: admin
  #     RUSTFS_SECRET_KEY: password
  #   volumes:
  #     - nestjs-starter-template-s3-volume:/data
  #   command: /data

volumes:
  nestjs-starter-template-db-volume:
  nestjs-starter-template-rabbitmq-volume:
  nestjs-starter-template-grafana-volume:
  # nestjs-starter-template-s3-volume:
